package com.sighware.mark.server.model;

public enum Status {
    MARK_AVAILABLE,
    MARK_PENDING_PAYMENT_BY_CHEQUE,
    MARK_SOLD_ISSUE_CERTIFICATE_TO_PURCHASER,
    REMOVE_MARK_FROM_SALE,
    MARK_ASSIGNED,
    MARK_PURCHASED_BY_PAYMENT_CARD_CERT_NOT_YET_ISSUED,
    DVLA_ACCREDITED_DEALER_SALE,
    ISSUE_DUPLICATE_CERTIFICATE,
    ISSUE_REPLACEMENT_CERTIFICATE,
    CERTIFICATE_ISSUED_PAYMENT_RECEIVED,
    MARK_STOPPED_NO_FURTHER_ACTION_ALLOWED,
    MARK_STOPPED_ASSIGNMENT_FEE_REPAID,
    DEALER_STOPPED,
    OFFENSIVE,
    CHEQUE_BANKED_NOT_YET_CLEARED,
    CERTIFICATE_ISSUED_PAYMENT_NOT_YEY_RECEIVED,
    MARK_ASSIGNED_PAYMENT_NOT_YEY_RECEIVED,
    MARK_STOPPED_CHEQUE_RETURNED,
    MARK_RESERVED_CHEQUE_OVERDUE,
    RD_CHEQUE_AFTER_V750_ISSUED
}
